### ISSUE TITLE
Progress is always NaN or 100

### ISSUE THREAD

**Issue by cmmartin** [sinnerschrader/react-over-scroll#10]
<img width="426" alt="screen shot 2018-03-23 at 5 07 03 pm" src="https://user-images.githubusercontent.com/2001903/37853344-ab18e982-2ebc-11e8-9f79-7056b3b255fb.png">

Just using the basic example from the readme

**Comment by 888jacklee** [comment]
I have the same issue

**Comment by pixelass** [comment]
should be resolved via: https://github.com/pixelass/react-over-scroll
