### ISSUE TITLE
Possible Windows error

### ISSUE THREAD

**Issue by bestwestern** [sinnerschrader/react-over-scroll#4]
I tried cloning, and then running npm install and npm start but I get this:
> NODE_ENV=production

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

**Comment by pixelass** [comment]
Thanks for reporting. I do not own a windows machine to test this.  
Is this a known issue with windows and node?  
Do you know if `BABEL_ENV` is supported?

If you can test it I'd be happy about a PullRequest.

**Comment by pixelass** [comment]
Also see: http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

**Comment by pixelass** [comment]
should be resolved via https://github.com/pixelass/react-over-scroll
